### ISSUE TITLE
isito install yaml file is mixed with istio.yaml and istio-demo.yaml

### ISSUE THREAD

**Issue by LillyWu** [istio/istio.github.io#1672]
In doc files,  the guidance shows install/cleanup istio with 

`kubectl apply -f install/kubernetes/istio.yaml`
and 
`kubectl apply -f install/kubernetes/istio-demo.yaml`

It looks confusing. And all the links to the source are broken as this yaml file doesn't exist in [istio/istio](https://github.com/istio/istio/tree/master/install/kubernetes)

In release-0.8, the file is `istio-demo.yaml`. Besides, this [PR](https://github.com/istio/istio/pull/6103/files) which changed the istio.yaml to istio-demo.yaml was merged 

So could anyone from the team could confirm which file will be used, then I'd like to update them.

**Comment by geeknoid** [comment]
The broken links are now fixed.

@sdake Care to add anything re the content?

**Comment by sdake** [comment]
@geeknoid sure.

**Comment by sdake** [comment]
Fixed here: https://github.com/istio/istio.github.io/pull/1696

This can be closed.

**Comment by LillyWu** [comment]
@sdake could you show me the link of the istio.yaml file, I still can't find it in  https://github.com/istio/istio/tree/master/install/kubernetes
and https://raw.githubusercontent.com/istio/istio/release-1.0/install/kubernetes/istio.yaml returns 404

**Comment by sdake** [comment]
@LillyWu within the tarball distributed by the test and release team, `istio-demo-auth.yaml `and `istio-demo.yaml` are produced.  In the repo, these files are not present.

**Comment by jaygorrell** [comment]
Just curious, what's the reason behind the "demo" name? It makes it sound like that's not intended for _really_ running Istio, outside of a concept demo.
